# Main Hydra configuration for DSCIM Refactoring
# @package _global_

defaults:
  - data_generation: default
  - computation: default
  - testing: default
  - _self_

# Override settings
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}

# Global metadata
version: "2.0.0"
description: "DSCIM Refactoring Project Configuration"
author: "DSCIM Refactoring Team"